### ISSUE TITLE
Weird formatting happened on a Dr. Venkman for Electron Cash

### ISSUE THREAD

**Issue by cculianu** [bauerj/crashhub#8]
Here is the relevant issue in Electron Cash:

https://github.com/fyookball/electrum/issues/832

Apparently something got formatted wrong and @marceloneil said it's a server-side thing.  @bauerj also said to post this here.  So here I am.

**Comment by marceloneil** [comment]
Thanks!
Just to clarify, it can be solved both client and server side (it probably should be fixed on both), but old clients will still send malformed requests so a server-side fix is more important.

**Comment by bauerj** [comment]
This was fixed in 91332fce1d65564abf3

**Comment by cculianu** [comment]
That was fast! ;)
