### ISSUE TITLE
Add link to full traceback for each report.

### ISSUE THREAD

**Issue by bauerj** [bauerj/crashhub#9]

**Comment by SomberNight** [comment]
is the db storing the reports publically accessible?
just wondering if there is a workaround to see the reports

**Comment by mhsmith** [comment]
Nothing's publicly accessible except for the URL to submit new reports. What information do you need that isn't already being posted to GitHub?

**Comment by SomberNight** [comment]
The report aggregation is not perfect; I would like to see individual reports (tracebacks) that have been aggregated into the same issue, as per topic :)

**Comment by mhsmith** [comment]
OK, if you let me know the GitHub issue link then I can probably get them out of the database for you.

**Comment by bauerj** [comment]
How? 🤔

**Comment by mhsmith** [comment]
I assumed he was talking about the Electron Cash crash reporter, which I host. But looking at his commit history, I guess he probably meant Electrum. Sorry for the confusion.

**Comment by mhsmith** [comment]
But looking at his commit history, I guess he probably meant Electrum.

**Comment by bauerj** [comment]
I added such a functionality in 3bab6f1. It will probably take a while to update all posts.
